export_if_exists ANSIBLE_HOME "$XDG_DATA_HOME/ansible"
export_if_exists BUNDLE_USER_CONFIG "$XDG_CONFIG_HOME/bundle"
export_if_exists BUNDLE_USER_CACHE "$XDG_CACHE_HOME/bundle"
export_if_exists BUNDLE_USER_PLUGIN= "$XDG_DATA_HOME/bundle"
export_if_exists CARGO_HOME "$XDG_DATA_HOME/cargo"
export_if_exists DOTNET_CLI_HOME "$XDG_DATA_HOME/dotnet"
export_if_exists GNUPGHOME "$XDG_DATA_HOME/gnupg"
export_if_exists GOPATH "$XDG_DATA_HOME/go"
export_if_exists NUGET_PACKAGES "$XDG_CACHE_HOME/NuGetPackages"
export_if_exists OMNISHARPHOME "$XDG_CONFIG_HOME/omnisharp"
export_if_exists RUSTUP_HOME "$XDG_DATA_HOME/rustup"
export_if_exists SCREENRC "$XDG_CONFIG_HOME/screen/screenrc"
export_if_exists TERMINFO "$XDG_DATA_HOME/terminfo"
export_if_exists TERMINFO_DIRS "$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export_if_exists WINEPREIFX "$XDG_DATA_HOME/wine"

export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
