#!/usr/bin/env bash
set -euo pipefail

## this script is run when yadm is first cloned to perform one-time setup tasks.
system_type=$(uname -s)
sys_hostname=$(hostname)
typeset -l sys_hostname

if [[ $sys_hostname == epic* ]] || [[ $sys_hostname == vm-bschafer ]]; then
    echo 'setting yadm config class to work'
    yadm config local.class work
fi

# init submodules, especially ohmyzsh
cd "$HOME" || exit
echo "Init submodules"
yadm submodule update --recursive --init

# install tmux plugin manager plugins
echo "Load tmux conf and install plugins"
tmux source ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins

if [ "$system_type" = "Darwin" ]; then
  if command -v brew 2>/dev/null; then
    echo "Homebrew already installed"
  else
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  brew install zsh tmux neovim
fi

# install packages
if [ "$system_type" = "Linux" ] ; then
    echo 'installing packages'
    if [ -f /etc/debian_version ]; then
	sudo apt update
	sudo apt install -y zsh tmux vim neovim python-pip
    elif [ -f /etc/arch-release ]; then
        sudo pacman -Sy --noconfirm zsh tmux vim neovim python-pip
    elif [ -f /etc/redhat-release ]; then
        EL_VERSION=$(cat /etc/redhat-release)
        if [[ "$EL_VERSION" == *8.* ]]; then
            sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        elif [[ "$EL_VERSION" == *7.* ]]; then
            sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        fi
        sudo yum install -y zsh tmux vim python3-pip
    fi
fi

echo "setting default shell to zsh, it'll prompt for your password"
chsh -s "$(command -v zsh)"

if command -v setxkbmap 2>/dev/null ; then
    echo 'mapping caps -> esc'
    setxkbmap -option caps:escape
fi

if command -v nvim 2>/dev/null ; then
    echo 'installing/updating neovim plugins'
    # update plugins
    nvim '+call minpac#update()' '+qall'
    echo
fi

exec_pip() {
    local args="$*"
    if [[ -z "$args" ]]; then
        echo "nothing doing"
    fi

    local pip_cmd

    if command -v pip ; then
        pip_cmd='pip'
    elif command -v pip3 ; then
        pip_cmd='pip3'
    elif python -m pip ; then
        pip_cmd='python -m pip'
    elif python3 -m pip ; then
        pip_cmd='python3 -m pip'
    else
        echo "unable to locate pip" >&2
    fi

    exec "$pip_cmd $args"
}

# python modules
echo "trying to install python packages"
exec_pip 'install pynvim'

echo 'all set, execing into zsh'
if ! [[ $SHELL == *zsh ]]; then exec zsh ; fi
