#!/usr/bin/env bash
set -x

## this script is run when yadm is first cloned to perform one-time setup tasks.
## as such, it should be written in pure bash and can't assume convenience things
## exist, yet.
system_type=$(uname -s)
sys_hostname=$(hostname)
typeset -l sys_hostname

# yadm config local.class work

# init submodules
cd "$HOME" || exit
echo "Init submodules"
test -d "$HOME/.oh-my-zsh" || git clone https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
yadm submodule update --recursive --init

# install tmux plugin manager plugins
echo "Load tmux conf and install plugins"
tmux source ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins

echo 'installing packages'
if [ "$system_type" = "Darwin" ]; then
  brew install \
      zsh tmux neovim wezterm gnu-sed gawk gnu-getopt gnu-units \
      bat ripgrep starship zoxide espanso jq
elif [ "$system_type" = "Linux" ] ; then
    if [ -f /etc/debian_version ]; then
        sudo apt-get update -q
        sudo apt-get install -yq \
            zsh tmux vim jq neovim ripgrep batcat starship \
            zoxide
    elif [ -f /etc/arch-release ]; then
        sudo pacman -Sy --noconfirm \
            zsh tmux vim neovim wezterm ripgrep bat starship zoxide yay jq
        yay -S espanso-wayland
    elif [ -f /etc/redhat-release ]; then
        EL_VERSION=$(cat /etc/redhat-release)
        if [[ "$EL_VERSION" == *8.* ]]; then
            sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        elif [[ "$EL_VERSION" == *7.* ]]; then
            sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        fi
        sudo dnf install -y zsh tmux vim
    fi
fi

echo "setting default shell to zsh, it'll prompt for your password"
chsh -s "$(command -v zsh)"

if command -v setxkbmap 2>/dev/null ; then
    echo 'mapping caps -> esc'
    setxkbmap -option caps:escape
fi

if command -v nvim 2>/dev/null ; then
    echo 'installing/updating neovim plugins'
    nvim '+Lazy sync' '+qall'
    echo
fi

echo 'all set, execing into zsh'
if ! [[ $SHELL == *zsh ]]; then exec zsh ; fi
