# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:

#########
# Dates #
#########
  - trigger: ".today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
    word: true
  - trigger: ".todays"
    replace: "{{mydate}} .bjs"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
    word: true

###################
# misc hotstrings #
###################

  - trigger: ".thx"
    replace: |-


        Thanks,
        Braxton

  - trigger: ".questions"
    replace: |-


        Let me know if you have any questions.

        Thanks,
        Braxton

######################
# Spanish diacritics #
######################

  - trigger: "\\~n"
    replace: "ñ"
  - trigger: "\\~N"
    replace: "Ñ"
  - trigger: "\\'a"
    replace: "á"
  - trigger: "\\'e"
    replace: "é"
  - trigger: "\\'i"
    replace: "í"
  - trigger: "\\'o"
    replace: "ó"
  - trigger: "\\'u"
    replace: "ú"
  - trigger: "\\'A"
    replace: "Á"
  - trigger: "\\'E"
    replace: "É"
  - trigger: "\\'I"
    replace: "Í"
  - trigger: "\\'O"
    replace: "Ó"
  - trigger: "\\'U"
    replace: "Ú"

# other diacritics
  - trigger: '\"a'
    replace: 'ä'
  - trigger: '\"A'
    replace: 'Ä'
  - trigger: '\"e'
    replace: 'ë'
  - trigger: '\"E'
    replace: 'Ë'
  - trigger: '\"i'
    replace: 'ï'
  - trigger: '\"I'
    replace: 'Ï'
  - trigger: '\"o'
    replace: 'ö'
  - trigger: '\"O'
    replace: 'Ö'
  - trigger: '\"u'
    replace: 'ü'
  - trigger: '\"U'
    replace: 'Ü'

  - trigger: '\~a'
    replace: 'ã'
  - trigger: '\~A'
    replace: 'Ã'
  - trigger: '\~o'
    replace: 'õ'
  - trigger: '\~O'
    replace: 'Õ'

######################
# weird other things #
######################

  - trigger: '\eth'
    replace: 'ð'
  - trigger: '\Eth'
    replace: 'Ð'
  - trigger: '\thorn'
    replace: 'þ'
    
###############
# expressives #
###############

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - triggers:
      - ":lennyface"
      - ":lenny"
    replace: "( ͡° ͜ʖ ͡°)"

  - triggers:
      - ":tm"
      - "(tm)"
    replace: "™"

  - trigger: "(r)"
    replace: "®"

  - trigger: "(c)"
    replace: "©"

##################
# script helpers #
##################

  - trigger: ".scriptheader"
    replace: |-
        ###############################################################################
        #
        # <description>
        #
        #     Usage: ./<scriptname>
        #
        #  Homepage: https://github.com/project/path
        #
        #    Author: Braxton Schafer <braxton@cmdcentral.xyz> (bjs)
        #
        # Changelog:
        #   - {{today}} .bjs:  Initial creation
        #
        ###############################################################################


    vars:
        - name: today
          type: date
          params:
              format: "%Y-%m-%d"

