#!/bin/bash

## this script is run when yadm is first cloned to perform one-time setup tasks.
system_type=$(uname -s)

# init submodules, especially ohmyzsh
cd "$HOME" || exit
echo "Init submodules"
yadm submodule update --recursive --init

# install tmux plugin manager plugins
tmux source ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins

if [ "$system_type" = "Darwin" ]; then
  if command -v brew 2>/dev/null; then
    echo "Homebrew already installed"
    exit 0
  fi
  echo "Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install packages
if [ "$system_type" = "Linux" ] && [ -f /etc/debian_version ]; then
	sudo apt update
	sudo apt install -y zsh tmux vim neovim
fi

# python modules
default_python_version=$(python --version 2>&1 | awk '{print $2}' | awk -F. '{print $1}')
if [ -z "${default_python_version+x}" ] && [ command -v pip ]; then
    pip install neovim
else
    echo "Not installing pynvim, since either Python or pip isn't installed."
fi
