#!/bin/bash

## this script is run when yadm is first cloned to perform one-time setup tasks.
system_type=$(uname -s)

# init submodules, especially ohmyzsh
cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init

# install tmux plugin manager plugins
tmux source ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins

if [ "$system_type" = "Darwin" ]; then
  if command -v brew 2>/dev/null; then
    echo "Homebrew already installed"
    exit 0
  fi
  echo "Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install packages
if [ "$system_type" = "Linux" ] && [ -f /etc/debian_version ]; then
	sudo apt update
	sudo apt install -y zsh tmux vim
fi
